name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: zyrastory/tools:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY,LINE_TOKEN,LINE_SECRET,ADMIN_TOKEN,REDIS_HOST
          port: 22
          script: |
            docker pull zyrastory/tools:latest
            docker stop fastapi || true
            docker rm fastapi || true
            docker run -d --name fastapi \
            -v /home/zyrastory/volume/tmp:/app/tmp \
            -e SUPABASE_URL="$SUPABASE_URL" \
            -e SUPABASE_SERVICE_KEY="$SUPABASE_KEY" \
            -e LINE_TOKEN="$LINE_TOKEN" \
            -e LINE_SECRET="$LINE_SECRET" \
            -e ADMIN_TOKEN="$ADMIN_TOKEN" \
            -e REDIS_HOST="$REDIS_HOST" \
            -p 8000:8000 zyrastory/tools:latest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_SECRET: ${{ secrets.LINE_SECRET }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          REDIS_HOST: "172.17.0.1"
